# Generated by Django 3.2 on 2021-04-28 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xcv_seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='dtm_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DTM Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seopage',
            name='dtm_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='DTM Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seopage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seosite',
            name='dtm_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DTM Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seosite',
            name='dtm_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='DTM Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seosite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
